// Dados mockados para demonstração

import { Vendedor, MetricasVendedor, Desafio, Premiacao, Lead } from './types';

export const vendedores: Vendedor[] = [
  {
    id: '1',
    nome: 'Carlos Silva',
    email: 'carlos@automotiva.com',
    telefone: '(11) 98765-4321',
    cargo: 'Vendedor Sênior',
    dataAdmissao: '2020-03-15',
  },
  {
    id: '2',
    nome: 'Ana Santos',
    email: 'ana@automotiva.com',
    telefone: '(11) 98765-4322',
    cargo: 'Vendedora Pleno',
    dataAdmissao: '2021-07-20',
  },
  {
    id: '3',
    nome: 'Roberto Lima',
    email: 'roberto@automotiva.com',
    telefone: '(11) 98765-4323',
    cargo: 'Vendedor Júnior',
    dataAdmissao: '2022-11-10',
  },
  {
    id: '4',
    nome: 'Juliana Costa',
    email: 'juliana@automotiva.com',
    telefone: '(11) 98765-4324',
    cargo: 'Vendedora Sênior',
    dataAdmissao: '2019-05-08',
  },
  {
    id: '5',
    nome: 'Pedro Oliveira',
    email: 'pedro@automotiva.com',
    telefone: '(11) 98765-4325',
    cargo: 'Vendedor Pleno',
    dataAdmissao: '2021-09-12',
  },
];

export const metricas: MetricasVendedor[] = [
  {
    vendedorId: '1',
    carrosVendidos: 12,
    agendamentos: 28,
    tempoMedioAtendimento: 45,
    scoreTotal: 950,
    scoreSemanal: 180,
    scoreMensal: 720,
    scoreAnual: 9500,
    metaAtingida: true,
    posicaoRanking: 1,
  },
  {
    vendedorId: '2',
    carrosVendidos: 10,
    agendamentos: 24,
    tempoMedioAtendimento: 38,
    scoreTotal: 880,
    scoreSemanal: 165,
    scoreMensal: 660,
    scoreAnual: 8800,
    metaAtingida: true,
    posicaoRanking: 2,
  },
  {
    vendedorId: '3',
    carrosVendidos: 6,
    agendamentos: 18,
    tempoMedioAtendimento: 52,
    scoreTotal: 620,
    scoreSemanal: 120,
    scoreMensal: 480,
    scoreAnual: 6200,
    metaAtingida: false,
    posicaoRanking: 5,
  },
  {
    vendedorId: '4',
    carrosVendidos: 11,
    agendamentos: 26,
    tempoMedioAtendimento: 42,
    scoreTotal: 920,
    scoreSemanal: 175,
    scoreMensal: 700,
    scoreAnual: 9200,
    metaAtingida: true,
    posicaoRanking: 3,
  },
  {
    vendedorId: '5',
    carrosVendidos: 8,
    agendamentos: 20,
    tempoMedioAtendimento: 48,
    scoreTotal: 740,
    scoreSemanal: 140,
    scoreMensal: 560,
    scoreAnual: 7400,
    metaAtingida: false,
    posicaoRanking: 4,
  },
];

export const desafios: Desafio[] = [
  {
    id: '1',
    titulo: 'Desafio Vendas de Dezembro',
    descricao: 'Venda 15 carros até o final do mês e ganhe R$ 5.000 de bônus',
    tipo: 'vendas',
    meta: 15,
    periodo: 'mensal',
    dataInicio: '2024-12-01',
    dataFim: '2024-12-31',
    premio: 'Bônus de R$ 5.000',
    valorPremio: 5000,
    status: 'ativo',
    participantes: ['1', '2', '3', '4', '5'],
    progresso: {
      '1': 12,
      '2': 10,
      '3': 6,
      '4': 11,
      '5': 8,
    },
  },
  {
    id: '2',
    titulo: 'Sprint Semanal de Agendamentos',
    descricao: 'Realize 30 agendamentos esta semana',
    tipo: 'agendamentos',
    meta: 30,
    periodo: 'semanal',
    dataInicio: '2024-12-16',
    dataFim: '2024-12-22',
    premio: 'Vale-presente R$ 500',
    valorPremio: 500,
    status: 'ativo',
    participantes: ['1', '2', '3', '4', '5'],
    progresso: {
      '1': 28,
      '2': 24,
      '3': 18,
      '4': 26,
      '5': 20,
    },
  },
  {
    id: '3',
    titulo: 'Excelência no Atendimento',
    descricao: 'Mantenha tempo médio de atendimento abaixo de 40 minutos',
    tipo: 'atendimento',
    meta: 40,
    periodo: 'mensal',
    dataInicio: '2024-12-01',
    dataFim: '2024-12-31',
    premio: 'Troféu + Reconhecimento',
    status: 'ativo',
    participantes: ['1', '2', '3', '4', '5'],
    progresso: {
      '1': 45,
      '2': 38,
      '3': 52,
      '4': 42,
      '5': 48,
    },
  },
];

export const premiacoes: Premiacao[] = [
  {
    id: '1',
    titulo: 'Viagem para Cancún',
    descricao: 'Viagem all-inclusive para 2 pessoas',
    tipo: 'viagem',
    requisitos: 'Ser o vendedor do ano (maior score anual)',
    vendedoresElegiveis: ['1', '4'],
  },
  {
    id: '2',
    titulo: 'Bônus Trimestral',
    descricao: 'Bônus de até R$ 10.000',
    tipo: 'bonus',
    valor: 10000,
    requisitos: 'Atingir 100% da meta trimestral',
    vendedoresElegiveis: ['1', '2', '4'],
  },
  {
    id: '3',
    titulo: 'iPhone 15 Pro',
    descricao: 'iPhone 15 Pro Max 256GB',
    tipo: 'produto',
    requisitos: 'Vender 50 carros no semestre',
    vendedoresElegiveis: ['1', '4'],
  },
  {
    id: '4',
    titulo: 'Vendedor do Mês',
    descricao: 'Reconhecimento público + Troféu + R$ 2.000',
    tipo: 'reconhecimento',
    valor: 2000,
    requisitos: 'Maior score mensal',
    vendedoresElegiveis: ['1'],
  },
];

export const leads: Lead[] = [
  {
    id: '1',
    nome: 'João Pereira',
    email: 'joao@email.com',
    telefone: '(11) 99999-1111',
    origem: 'Site',
    status: 'qualificado',
    vendedorResponsavel: '1',
    veiculoInteresse: 'SUV Compass',
    valor: 180000,
    probabilidade: 70,
    dataCriacao: '2024-12-10',
    dataUltimaInteracao: '2024-12-18',
    proximaAcao: 'Test-drive agendado',
    dataProximaAcao: '2024-12-20',
    arquivos: [],
    historico: [],
  },
  {
    id: '2',
    nome: 'Maria Fernandes',
    email: 'maria@email.com',
    telefone: '(11) 99999-2222',
    origem: 'Instagram',
    status: 'proposta',
    vendedorResponsavel: '2',
    veiculoInteresse: 'Sedan Civic',
    valor: 150000,
    probabilidade: 85,
    dataCriacao: '2024-12-08',
    dataUltimaInteracao: '2024-12-19',
    proximaAcao: 'Enviar proposta final',
    dataProximaAcao: '2024-12-21',
    arquivos: [],
    historico: [],
  },
  {
    id: '3',
    nome: 'Ricardo Alves',
    email: 'ricardo@email.com',
    telefone: '(11) 99999-3333',
    origem: 'Indicação',
    status: 'negociacao',
    vendedorResponsavel: '4',
    veiculoInteresse: 'Pickup Hilux',
    valor: 250000,
    probabilidade: 60,
    dataCriacao: '2024-12-05',
    dataUltimaInteracao: '2024-12-19',
    proximaAcao: 'Negociar condições de pagamento',
    dataProximaAcao: '2024-12-22',
    arquivos: [],
    historico: [],
  },
];

export const dadosGraficoVendas = [
  { mes: 'Jul', vendas: 45, meta: 50 },
  { mes: 'Ago', vendas: 52, meta: 50 },
  { mes: 'Set', vendas: 48, meta: 50 },
  { mes: 'Out', vendas: 61, meta: 55 },
  { mes: 'Nov', vendas: 55, meta: 55 },
  { mes: 'Dez', vendas: 47, meta: 60 },
];

export const dadosGraficoScore = [
  { nome: 'Carlos', score: 950 },
  { nome: 'Juliana', score: 920 },
  { nome: 'Ana', score: 880 },
  { nome: 'Pedro', score: 740 },
  { nome: 'Roberto', score: 620 },
];
